# Generated by Django 4.2.7 on 2023-11-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eaddress',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
