# Generated by Django 4.2.7 on 2023-11-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_eaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eaddress',
        ),
    ]
