# Generated by Django 4.2.7 on 2023-11-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_image_alter_employee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
