# Generated by Django 4.2.7 on 2023-11-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_image_alter_employee_eemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
